module.exports = {
    BOARD: '#board',
    MESSAGE: '#message',
    BLUE_CHECKER: '[src="me1.gif"]',
    RESTART_BUTTON: 'a:text("Restart...")',
    CHECKER_YOU1: 'you1.gif',
    CHECKER_YOU2: 'you2.gif',
    CHECKER_GRAY: 'gray.gif',
    MOVE_1_CURRENT: '[name=space62]',
    MOVE_1_TARGET: '[name=space73]',
    MOVE_2_CURRENT: '[name=space42]',
    MOVE_2_TARGET: '[name=space53]',
    MOVE_3_CURRENT: '[name=space51]',
    MOVE_3_TARGET: '[name=space62]',
    MOVE_4_CURRENT: '[name=space40]',
    MOVE_4_TARGET: '[name=space51]',
    MOVE_5_CURRENT: '[name=space53]',
    MOVE_5_TARGET: '[name=space35]',
};
